// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "eu-west-1",
    "aws_appsync_graphqlEndpoint": "https://eropmr6xmjenrbzi64p53q2pzq.appsync-api.eu-west-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-oeylcu5a55aufis5mwcubimhha",
    "aws_cognito_identity_pool_id": "eu-west-1:6302dc37-69d7-4ae2-9d17-230c12fd6f90",
    "aws_cognito_region": "eu-west-1",
    "aws_mobile_analytics_app_id": "df0443df2f154a3aa6c418c8a44abf69",
    "aws_mobile_analytics_app_region": "eu-west-1",
    "aws_content_delivery_bucket": "livitysoundra-20190104161948-hostingbucket",
    "aws_content_delivery_bucket_region": "eu-west-1",
    "aws_content_delivery_url": "http://livitysoundra-20190104161948-hostingbucket.s3-website-eu-west-1.amazonaws.com"
};


export default awsmobile;
